version: "3.3"

services:
  drone:
    image: drone/drone:2
    environment:
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=https
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_USER_CREATE=username:alessandro1105,admin:true
      - DRONE_USER_FILTER=dartmoon-io
      - DRONE_TLS_AUTOCERT=false
    volumes:
      - "/var/docker/drone:/data"
    labels:
      - "traefik.http.routers.drone.rule=Host(`drone.yourdomain.ext`)"
      - "traefik.http.routers.drone.entrypoints=web"
      - "traefik.http.routers.drone.middlewares=https-redirect"
      - "traefik.http.routers.drone-secure.rule=Host(`drone.yourdomain.ext`)"
      - "traefik.http.routers.drone-secure.entrypoints=websecure"
      - "traefik.http.routers.drone-secure.tls.certresolver=letsencrypt"
    restart: always
    networks:
      - traefik

  drone-runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=${DRONE_RPC_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - traefik
      
networks:
  traefik:
    external: true