version: "3.3"

services:
  drone:
    image: drone/drone:2
    environment:
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=https
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_USER_CREATE=username:alessandro1105,admin:true
      - DRONE_USER_FILTER=dartmoon-io
      - DRONE_TLS_AUTOCERT=false
    volumes:
      - "/var/lib/drone:/data"
    labels:
      - "traefik.http.routers.drone.rule=Host(`drone.dartmoon.test`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
    restart: always
    networks:
      - public

  drone-runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=https
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NAME=${HOSTNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - public
      
networks:
  public:
    external: true