version: "3"
services:

  outline:
    image: outlinewiki/outline:0.69.2
    environment:
      - NODE_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - PGSSLMODE=${PGSSLMODE}
      - REDIS_URL=redis://redis:6379
      - URL=https://${TRAEFIK_HOST}
      - PORT=3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_ACCELERATE_URL=${AWS_S3_ACCELERATE_URL}
      - AWS_S3_UPLOAD_BUCKET_URL=${AWS_S3_UPLOAD_BUCKET_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=${AWS_S3_UPLOAD_BUCKET_NAME}
      - AWS_S3_UPLOAD_MAX_SIZE=${AWS_S3_UPLOAD_MAX_SIZE}
      - AWS_S3_FORCE_PATH_STYLE=${AWS_S3_FORCE_PATH_STYLE}
      - AWS_S3_ACL=${AWS_S3_ACL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CDN_URL=https://${TRAEFIK_HOST}
      - FORCE_HTTPS=true
      - ENABLE_UPDATES=false
      - WEB_CONCURRENCY=1
      - MAXIMUM_IMPORT_SIZE=5120000
      - LOG_LEVEL=info
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_REPLY_EMAIL=${SMTP_REPLY_EMAIL}
      - SMTP_TLS_CIPHERS=${SMTP_TLS_CIPHERS}
      - SMTP_SECURE=${SMTP_SECURE}
      - DEFAULT_LANGUAGE=it_IT
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_REQUESTS=1000
      - RATE_LIMITER_DURATION_WINDOW=60
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.outline.entrypoints=web"
      - "traefik.http.routers.outline.middlewares=https-redirect"
      - "traefik.http.routers.outline-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.outline-secure.entrypoints=websecure"
      - "traefik.http.routers.outline-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.outline-secure.loadbalancer.server.port=3000"
      - "traefik.http.services.outline-secure.loadbalancer.server.scheme=http"
    restart: always
    networks:
      - traefik
      - outline
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.0.9
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline

  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - "/var/docker/outline/volumes/postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - outline

networks:
  outline:
    driver: bridge
  traefik:
    external: true