version: "3.3"

services:
  traefik:
    image: "traefik:v2.9"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api.dashboard=true

      # - --certificatesresolvers.myresolver.acme.tlschallenge=true
      # - --certificatesresolvers.myresolver.acme.email=postmaster@example.com
      # - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

      # - --api.insecure
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      # - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.test`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
    restart: always
    networks:
      - public
      
networks:
  public:
    external: true