version: '3.9'

services:
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="true"
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - passbolt

  passbolt:
    image: passbolt/passbolt:3.8.3-1-ce
    depends_on:
      - mariadb
    environment:
      - APP_FULL_BASE_URL=https://${TRAEFIK_HOST}
      - DATASOURCES_DEFAULT_HOST=mariadb
      - DATASOURCES_DEFAULT_USERNAME=${DATABASE_USER}
      - DATASOURCES_DEFAULT_PASSWORD=${DATABASE_PASSWORD}
      - DATASOURCES_DEFAULT_DATABASE=${DATABASE_NAME}
      - EMAIL_DEFAULT_FROM=${EMAIL_DEFAULT_FROM}
      - EMAIL_DEFAULT_FROM_NAME=${EMAIL_DEFAULT_FROM_NAME}
      - EMAIL_TRANSPORT_DEFAULT_HOST=${EMAIL_TRANSPORT_DEFAULT_HOST}
      - EMAIL_TRANSPORT_DEFAULT_PORT=${EMAIL_TRANSPORT_DEFAULT_PORT}
      - EMAIL_TRANSPORT_DEFAULT_TLS=${EMAIL_TRANSPORT_DEFAULT_TLS}
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=${EMAIL_TRANSPORT_DEFAULT_USERNAME}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${EMAIL_TRANSPORT_DEFAULT_PASSWORD}
      - SECURITY_SALT=${SECURITY_SALT}
      - PASSBOLT_KEY_NAME=${PASSBOLT_KEY_NAME}
      - PASSBOLT_KEY_EMAIL=${PASSBOLT_KEY_EMAIL}
    volumes:
      - "gpg:/etc/passbolt/gpg"
      - "jwt:/etc/passbolt/jwt"
    command: ["/usr/bin/wait-for.sh", "-t", "0", "mariadb:3306", "--", "/docker-entrypoint.sh"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.passbolt.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.passbolt.entrypoints=web"
      - "traefik.http.routers.passbolt.middlewares=https-redirect"
      - "traefik.http.routers.passbolt-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.passbolt-secure.entrypoints=websecure"
      - "traefik.http.routers.passbolt-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.passbolt-secure.loadbalancer.server.port=443"
      - "traefik.http.services.passbolt-secure.loadbalancer.server.scheme=https"
    restart: always
    networks:
      - traefik
      - passbolt
      
volumes:
  mysql:
  gpg:
  jwt:

networks:
  passbolt:
  traefik:
    external: true
