services:
  registry:
    image: registry:2.8
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_SECURE=true
      - REGISTRY_STORAGE_S3_REGION=${REGISTRY_STORAGE_S3_REGION}
      - REGISTRY_STORAGE_S3_REGIONENDPOINT=${REGISTRY_STORAGE_S3_REGIONENDPOINT}
      - REGISTRY_STORAGE_S3_BUCKET=${REGISTRY_STORAGE_S3_BUCKET}
      - REGISTRY_STORAGE_S3_ACCESSKEY=${REGISTRY_STORAGE_S3_ACCESSKEY}
      - REGISTRY_STORAGE_S3_SECRETKEY=${REGISTRY_STORAGE_S3_SECRETKEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.registry-auth.basicauth.users=${REGISTRY_BASIC_AUTH_USERS}"
      - "traefik.http.routers.registry.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.registry.entrypoints=web"
      - "traefik.http.routers.registry.middlewares=https-redirect"
      - "traefik.http.routers.registry-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.registry-secure.entrypoints=websecure"
      - "traefik.http.routers.registry-secure.middlewares=registry-auth"
      - "traefik.http.routers.registry-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.registry-secure.loadbalancer.server.port=5000"
      - "traefik.http.services.registry-secure.loadbalancer.server.scheme=http"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true