version: "3"
services:

  portainer-agent:
    image: portainer/agent:2.16.2
    container_name: portainer-edge-agent
    environment:
      - EDGE=${EDGE}
      - EDGE_ID=${EDGE_ID}
      - EDGE_KEY=${EDGE_KEY}
      - EDGE_INSECURE_POLL=${EDGE_INSECURE_POLL}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      - "/:/host"
      - "/var/docker/portainer-agent/volumes/data:/data"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"