services:
  portainer:
    image: portainer/portainer-ee:2.25.1
    container_name: portainer
    volumes:
      - "/var/docker/portainer/volumes/data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9443:9443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      # - "traefik.http.routers.portainer.middlewares=ipwhitelist,https-redirect"
      - "traefik.http.routers.portainer-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      # - "traefik.http.routers.portainer-secure.middlewares=ipwhitelist"
      - "traefik.http.routers.portainer-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9443"
      - "traefik.http.services.portainer-secure.loadbalancer.server.scheme=https"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true