services:
  mailserver:
    image: roundcube/roundcubemail:1.6.2-apache
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=${ROUNDCUBEMAIL_DEFAULT_HOST}
      - ROUNDCUBEMAIL_DEFAULT_PORT=${ROUNDCUBEMAIL_DEFAULT_PORT}
      - ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}
      - ROUNDCUBEMAIL_SMTP_PORT=${ROUNDCUBEMAIL_SMTP_PORT}
    volumes:
      - /var/docker/roundcube/volumes/config:/var/roundcube/config
      - /var/docker/roundcube/volumes/db:/var/roundcube/db
      - /var/docker/roundcube/volumes/temp:/tmp/roundcube-temp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.roundcube.entrypoints=web"
      - "traefik.http.routers.roundcube.middlewares=https-redirect"
      - "traefik.http.routers.roundcube-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.roundcube-secure.entrypoints=websecure"
      - "traefik.http.routers.roundcube-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.roundcube-secure.loadbalancer.server.port=80"
      - "traefik.http.services.roundcube-secure.loadbalancer.server.scheme=http"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true

